@startuml Диаграмма_Вариантов_Использования_ReadTracker

skinparam usecaseBorderColor #333
skinparam usecaseBackgroundColor #EEE
skinparam actorStyle awesome

actor "Пользователь" as User

rectangle "Система Read-Tracker" {

  ' ===== Общие сценарии =====
  User --> (Просмотр библиотеки)
  User --> (Поиск книг)
  User --> (Просмотр статистики чтения)

  (Просмотр статистики чтения) --> (Расчёт статистики) : <<include>>

  ' ===== Книги =====
  User --> (Добавить книгу)
  User --> (Редактировать книгу)
  User --> (Удалить книгу)
  User --> (Изменить статус книги)

  (Добавить книгу) --> (Проверка данных) : <<include>>
  (Редактировать книгу) --> (Проверка данных) : <<include>>

  ' ===== Сессии чтения =====
  User --> (Добавить сессию чтения)
  User --> (Редактировать сессию чтения)
  User --> (Удалить сессию чтения)

  (Добавить сессию чтения) --> (Проверка данных) : <<include>>
  (Редактировать сессию чтения) --> (Проверка данных) : <<include>>

  (Добавить сессию чтения) --> (Пересчитать прогресс книги) : <<include>>
  (Удалить сессию чтения) --> (Пересчитать прогресс книги) : <<include>>

  (Автоматически изменить статус книги) ..> (Пересчитать прогресс книги) : <<extend>>

  ' ===== Жанры =====
  User --> (Добавить жанр)
  User --> (Редактировать жанр)
  User --> (Удалить жанр)

  (Добавить жанр) --> (Проверка данных) : <<include>>
  (Редактировать жанр) --> (Проверка данных) : <<include>>
}

@enduml
