@startuml
actor Пользователь
participant UI
participant "SessionService" as Service
participant DB

Пользователь -> UI : добавить сессию чтения
UI -> Service : createSession(data)
activate Service

Service -> DB : insert ReadingSession
activate DB
DB --> Service
deactivate DB

alt Прочитаны все страницы книги
  Service -> DB : update Book status = "finished"
else Прочитана часть книги
  Service -> DB : update Book progress
end

Service --> UI : сессия сохранена
deactivate Service
@enduml
