@startuml
actor Пользователь
participant UI
participant "BookService" as Service
participant DB

Пользователь -> UI : открыть форму добавления книги
UI -> Service : addBook(data)
activate Service

Service -> DB : insert Book
activate DB
DB --> Service
deactivate DB

opt Пользователь указал статус
  Service -> DB : update status
end

Service --> UI : книга добавлена
deactivate Service
@enduml
